modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"
issueTrackerURL="https://github.com/TathanDev/FalloutCraft/issues"


[[mods]]
modId="falloutcraft"
version="${file.jarVersion}"
displayName="Fallout Craft"
#logoFile="examplemod.png"
credits=""
authors="TATHAN"
description='''
Falloout Craft is a mod that adds in Fallout themed items, blocks,structures and more...
Explore a devastated wasteland, fight raiders, and find rare loot!
'''
[[dependencies.falloutcraft]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.falloutcraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
