modLoader="javafml"
loaderVersion="[44,)"
license="All rights reserved"
issueTrackerURL="https://github.com/TathanDev/FalloutCraft/issues"


[[mods]]
modId="falloutcraft"
version="${file.jarVersion}"
displayName="Fallout Craft"
logoFile="falloutcraft.png"
credits=""
authors="TATHAN"
description='''
Fallout Craft is a mod that adds in Fallout themed items, blocks,structures and more...
Explore a devastated wasteland, find structures from an other life, and survive!
'''

[[dependencies.falloutcraft]]
    modId="forge"
    mandatory=true
    versionRange="[44,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.falloutcraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.20)"
    ordering="NONE"
    side="BOTH"


